# Generated by Django 2.0.2 on 2018-03-31 13:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate', models.CharField(max_length=64)),
                ('certificate_english', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=64)),
                ('city_english', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=64)),
                ('country', models.CharField(choices=[('Poland', 'Poland'), ('United Kingdom', 'United Kingdom'), ('Germany', 'Germany')], default='Poland', max_length=64)),
                ('description', models.CharField(max_length=9000)),
                ('salary_from', models.IntegerField()),
                ('salary_to', models.IntegerField()),
                ('wage_per_hour', models.IntegerField()),
                ('employment_status', models.CharField(choices=[('Poland', 'Poland'), ('United Kingdom', 'United Kingdom'), ('Germany', 'Germany')], default='Poland', max_length=64)),
                ('working_hours', models.CharField(max_length=64)),
                ('experience', models.IntegerField()),
                ('requirements', models.CharField(max_length=9000)),
                ('education_level', models.CharField(max_length=64)),
                ('benefits_description', models.CharField(max_length=9000)),
                ('company_description', models.CharField(max_length=9000)),
                ('company_name', models.CharField(max_length=128)),
                ('required_docs', models.CharField(max_length=64)),
                ('clause', models.CharField(max_length=512)),
                ('ref_number', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When offer was created', verbose_name='Created at')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('certificates', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='joboffers.Certificate')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='joboffers.City')),
            ],
        ),
    ]
