# Generated by Django 2.0.2 on 2018-04-23 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('joboffers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='joboffers.City'),
        ),
        migrations.AddField(
            model_name='offer',
            name='country',
            field=models.CharField(choices=[('Poland', 'Poland'), ('United Kingdom', 'United Kingdom'), ('Germany', 'Germany')], default='Poland', max_length=64),
        ),
        migrations.AddField(
            model_name='offer',
            name='description',
            field=models.CharField(max_length=9000, null=True),
        ),
    ]
