# Generated by Django 2.0.2 on 2018-04-23 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joboffers', '0002_auto_20180423_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='employment_status',
            field=models.CharField(choices=[('CONTRACT_WITH_NO_PERIOD', 'Employment contract for an unspecified period'), ('Employment contract for a specified period/fixed term', 'Employment contract for a specified period/fixed term'), ('B2B agreement', 'B2B agreement'), ('Project delivery contract', 'Project delivery contract')], default='CONTRACT_WITH_NO_PERIOD', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='salary_from',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='salary_to',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='wage_per_hour',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='working_hours',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
