# Generated by Django 2.0.2 on 2018-03-12 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joboffers', '0003_offer_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='title',
            new_name='position',
        ),
        migrations.AlterField(
            model_name='offer',
            name='company_name',
            field=models.CharField(max_length=128),
        ),
    ]
