# Generated by Django 2.0.2 on 2018-04-24 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joboffers', '0003_auto_20180423_1732'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='wage_per_hour',
            new_name='wage_per_hour_from',
        ),
        migrations.AddField(
            model_name='offer',
            name='wage_per_hour_to',
            field=models.IntegerField(null=True),
        ),
    ]
