# Generated by Django 2.0.2 on 2018-04-24 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joboffers', '0005_auto_20180424_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='description',
            field=models.CharField(max_length=9000, null=True),
        ),
    ]
