# Generated by Django 2.0.2 on 2018-04-24 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('joboffers', '0006_auto_20180424_1650'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='working_hours',
        ),
        migrations.AddField(
            model_name='offer',
            name='benefits_description',
            field=models.CharField(blank=True, max_length=9000, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='certificates',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='joboffers.Certificate'),
        ),
        migrations.AddField(
            model_name='offer',
            name='clause',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='company_description',
            field=models.CharField(blank=True, max_length=9000, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='company_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='education_level',
            field=models.CharField(blank=True, choices=[('Primary education', 'Primary education'), ('Secondary education', 'Secondary education'), ('Higher education', 'Higher education')], max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='experience',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='ref_number',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='required_docs',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='requirements',
            field=models.CharField(blank=True, max_length=9000, null=True),
        ),
    ]
