# Generated by Django 2.0.2 on 2018-05-06 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('joboffers', '0007_auto_20180424_1719'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='certificates',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='education_level',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='experience',
        ),
    ]
