# Generated by Django 2.0.2 on 2018-05-10 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joboffers', '0009_auto_20180510_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='benefits_description',
            field=models.CharField(blank=True, max_length=9000, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='clause',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='company_description',
            field=models.CharField(blank=True, max_length=9000, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='description',
            field=models.CharField(max_length=9000, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='employment_status',
            field=models.CharField(blank=True, choices=[('CONTRACT WITH NO PERIOD', 'Employment contract for an unspecified period'), ('Employment contract for a specified period/fixed term', 'Employment contract for a specified period/fixed term'), ('B2B agreement', 'B2B agreement'), ('Project delivery contract', 'Project delivery contract')], default='CONTRACT WITH NO PERIOD', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='ref_number',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='required_docs',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='requirements',
            field=models.CharField(blank=True, max_length=9000, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='salary_from',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='salary_to',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='wage_per_hour_from',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='wage_per_hour_to',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
