# Generated by Django 2.0.2 on 2018-05-13 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('joboffers', '0011_offer_contact_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='certificate_english',
        ),
        migrations.RemoveField(
            model_name='city',
            name='city_english',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='country',
        ),
    ]
